///// ian:accounts-ui-bootstrap-3 configuration    starts here //

Accounts.ui.config({
    requestPermissions: {},
    extraSignupFields: [{
        fieldName: 'username',
        fieldLabel: 'Username',
        inputType: 'text',
        visible: true,
        validate: function(value, errorFunction) {
          if (!value) {
            errorFunction("Please write your user name");
            return false;
          } else {
            return true;
          }
        }
    }, {
        fieldName: 'first-name',
        fieldLabel: 'Fast name',
        inputType: 'text',
        visible: true,
    }, {
        fieldName: 'last-name',
        fieldLabel: 'Last name',
        inputType: 'text',
        visible: true,
    }, {
        fieldName: 'gender',
        showFieldLabel: false,      // If true, fieldLabel will be shown before radio group
        fieldLabel: 'Gender',
        inputType: 'radio',
        radioLayout: 'vertical',    // It can be 'inline' or 'vertical'
        data: [{                    // Array of radio options, all properties are required
        id: 1,                  // id suffix of the radio element
            label: 'Male',          // label for the radio element
            value: 'm'              // value of the radio element, this will be saved.
          }, {
            id: 2,
            label: 'Female',
            value: 'f',
            checked: 'checked'
        }],
        visible: true
    }, {
        fieldName: 'country',
        fieldLabel: 'Country',
        inputType: 'select',
        showFieldLabel: true,
        empty: 'Please select your country of residence',
        data: [{ 
                id: 1, 
                label: 'Andorra', 
                value: 'ad' 
            },

            { 
                id: 2, 
                label: 'United Arab Emirates', 
                value: 'ae' 
            },
            
            { 
                id: 3, 
                label: 'Afghanistan', 
                value: 'af' 
            },
            
            { 
                id: 4, 
                label: 'Antigua and Barbuda', 
                value: 'ag' 
            },
            { 
                id: 5, 
                label: 'Anguilla', 
                value: 'ai' },
            {   id: 6, 
                label: 'Albania', 
                value: 'al' 
            },
            
            { 
                id: 7, 
                label: 'Armenia', 
                value: 'am' 
            },
            
            { 
                id: 8, 
                label: 'Netherlands Antilles', 
                value: 'an' 
            },
            
            { id: 9, label: 'Angola', value: 'ao' },
            { id: 10, label: 'Antarctica', value: 'aq' },
            { id: 11, label: 'Argentina', value: 'ar' },
            { id: 12, label: 'Old style Arpanet', value: 'arpa' },
            { id: 13, label: 'American Samoa', value: 'as' },
            { id: 14, label: 'Austria', value: 'at' },
            { id: 15, label: 'Australia', value: 'au' },
            { id: 16, label: 'Aruba', value: 'aw' },
            { id: 17, label: 'Azerbaidjan', value: 'az' },
            { id: 18, label: 'Bosnia-Herzegovina', value: 'ba' },
            { id: 19, label: 'Barbados', value: 'bb' },
            { id: 20, label: 'Bangladesh', value: 'bd' },
            { id: 21, label: 'Belgium', value: 'be' },
            { id: 22, label: 'Burkina Faso', value: 'bf' },
            { id: 23, label: 'Bulgaria', value: 'bg' },
            { id: 24, label: 'Bahrain', value: 'bh' },
            { id: 25, label: 'Burundi', value: 'bi' },
            { id: 26, label: 'Benin', value: 'bj' },
            { id: 27, label: 'Bermuda', value: 'bm' },
            { id: 28, label: 'Brunei Darussalam', value: 'bn' },
            { id: 29, label: 'Bolivia', value: 'bo' },
            { id: 30, label: 'Brazil', value: 'br' },
            { id: 31, label: 'Bahamas', value: 'bs' },
            { id: 32, label: 'Bhutan', value: 'bt' },
            { id: 33, label: 'Bouvet Island', value: 'bv' },
            { id: 34, label: 'Botswana', value: 'bw' },
            { id: 35, label: 'Belarus', value: 'by' },
            { id: 36, label: 'Belize', value: 'bz' },
            { id: 37, label: 'Canada', value: 'ca' },
            { id: 38, label: 'Cocos (Keeling) Islands', value: 'cc' },
            { id: 39, label: 'Central African Republic', value: 'cf' },
            { id: 40, label: 'Congo', value: 'cg' },
            { id: 41, label: 'Switzerland', value: 'ch' },
            { id: 42, label: 'Ivory Coast (Cote D\'Ivoire)', value: 'ci' },
            { id: 43, label: 'Cook Islands', value: 'ck' },
            { id: 44, label: 'Chile', value: 'cl' },
            { id: 45, label: 'Cameroon', value: 'cm' },
            { id: 46, label: 'China', value: 'cn' },
            { id: 47, label: 'Colombia', value: 'co' },
            { id: 48, label: 'Commercial', value: 'com' },
            { id: 49, label: 'Costa Rica', value: 'cr' },
            { id: 50, label: 'Former Czechoslovakia', value: 'cs' },
            { id: 51, label: 'Cuba', value: 'cu' },
            { id: 52, label: 'Cape Verde', value: 'cv' },
            { id: 53, label: 'Christmas Island', value: 'cx' },
            { id: 54, label: 'Cyprus', value: 'cy' },
            { id: 55, label: 'Czech Republic', value: 'cz' },
            { id: 56, label: 'Germany', value: 'de' },
            { id: 57, label: 'Djibouti', value: 'dj' },
            { id: 58, label: 'Denmark', value: 'dk' },
            { id: 59, label: 'Dominica', value: 'dm' },
            { id: 60, label: 'Dominican Republic', value: 'do' },
            { id: 61, label: 'Algeria', value: 'dz' },
            { id: 62, label: 'Ecuador', value: 'ec' },
            { id: 63, label: 'USA Educational', value: 'edu' },
            { id: 64, label: 'Estonia', value: 'ee' },
            { id: 65, label: 'Egypt', value: 'eg' },
            { id: 66, label: 'Western Sahara', value: 'eh' },
            { id: 67, label: 'Eritrea', value: 'er' },
            { id: 68, label: 'Spain', value: 'es' },
            { id: 69, label: 'Ethiopia', value: 'et' },
            { id: 70, label: 'Finland', value: 'fi' },
            { id: 71, label: 'Fiji', value: 'fj' },
            { id: 72, label: 'Falkland Islands', value: 'fk' },
            { id: 73, label: 'Micronesia', value: 'fm' },
            { id: 74, label: 'Faroe Islands', value: 'fo' },
            { id: 75, label: 'France', value: 'fr' },
            { id: 76, label: 'France (European Territory)', value: 'fx' },
            { id: 77, label: 'Gabon', value: 'ga' },
            { id: 78, label: 'Great Britain', value: 'gb' },
            { id: 79, label: 'Grenada', value: 'gd' },
            { id: 80, label: 'Georgia', value: 'ge' },
            { id: 81, label: 'French Guyana', value: 'gf' },
            { id: 82, label: 'Ghana', value: 'gh' },
            { id: 83, label: 'Gibraltar', value: 'gi' },
            { id: 84, label: 'Greenland', value: 'gl' },
            { id: 85, label: 'Gambia', value: 'gm' },
            { id: 86, label: 'Guinea', value: 'gn' },
            { id: 87, label: 'USA Government', value: 'gov' },
            { id: 88, label: 'Guadeloupe (French)', value: 'gp' },
            { id: 89, label: 'Equatorial Guinea', value: 'gq' },
            { id: 90, label: 'Greece', value: 'gr' },
            { id: 91, label: 'S. Georgia & S. Sandwich Isls.', value: 'gs' },
            { id: 92, label: 'Guatemala', value: 'gt' },
            { id: 93, label: 'Guam (USA)', value: 'gu' },
            { id: 94, label: 'Guinea Bissau', value: 'gw' },
            { id: 95, label: 'Guyana', value: 'gy' },
            { id: 96, label: 'Hong Kong', value: 'hk' },
            { id: 97, label: 'Heard and McDonald Islands', value: 'hm' },
            { id: 98, label: 'Honduras', value: 'hn' },
            { id: 99, label: 'Croatia', value: 'hr' },
            { id: 100, label: 'Haiti', value: 'ht' },
            { id: 101, label: 'Hungary', value: 'hu' },
            { id: 102, label: 'Indonesia', value: 'id' },
            { id: 103, label: 'Ireland', value: 'ie' },
            { id: 104, label: 'Israel', value: 'il' },
            { id: 105, label: 'India', value: 'in' },
            { id: 106, label: 'International', value: 'int' },
            { id: 107, label: 'British Indian Ocean Territory', value: 'io' },
            { id: 108, label: 'Iraq', value: 'iq' },
            { id: 109, label: 'Iran', value: 'ir' },
            { id: 110, label: 'Iceland', value: 'is' },
            { id: 111, label: 'Italy', value: 'it' },
            { id: 112, label: 'Jamaica', value: 'jm' },
            { id: 113, label: 'Jordan', value: 'jo' },
            { id: 114, label: 'Japan', value: 'jp' },
            { id: 115, label: 'Kenya', value: 'ke' },
            { id: 116, label: 'Kyrgyzstan', value: 'kg' },
            { id: 117, label: 'Cambodia', value: 'kh' },
            { id: 118, label: 'Kiribati', value: 'ki' },
            { id: 119, label: 'Comoros', value: 'km' },
            { id: 120, label: 'Saint Kitts & Nevis Anguilla', value: 'kn' },
            { id: 121, label: 'North Korea', value: 'kp' },
            { id: 122, label: 'South Korea', value: 'kr' },
            { id: 123, label: 'Kuwait', value: 'kw' },
            { id: 124, label: 'Cayman Islands', value: 'ky' },
            { id: 125, label: 'Kazakhstan', value: 'kz' },
            { id: 126, label: 'Laos', value: 'la' },
            { id: 127, label: 'Lebanon', value: 'lb' },
            { id: 128, label: 'Saint Lucia', value: 'lc' },
            { id: 129, label: 'Liechtenstein', value: 'li' },
            { id: 130, label: 'Sri Lanka', value: 'lk' },
            { id: 131, label: 'Liberia', value: 'lr' },
            { id: 132, label: 'Lesotho', value: 'ls' },
            { id: 133, label: 'Lithuania', value: 'lt' },
            { id: 134, label: 'Luxembourg', value: 'lu' },
            { id: 135, label: 'Latvia', value: 'lv' },
            { id: 136, label: 'Libya', value: 'ly' },
            { id: 137, label: 'Morocco', value: 'ma' },
            { id: 138, label: 'Monaco', value: 'mc' },
            { id: 139, label: 'Moldavia', value: 'md' },
            { id: 140, label: 'Madagascar', value: 'mg' },
            { id: 141, label: 'Marshall Islands', value: 'mh' },
            { id: 142, label: 'USA Military', value: 'mil' },
            { id: 143, label: 'Macedonia', value: 'mk' },
            { id: 144, label: 'Mali', value: 'ml' },
            { id: 145, label: 'Myanmar', value: 'mm' },
            { id: 146, label: 'Mongolia', value: 'mn' },
            { id: 147, label: 'Macau', value: 'mo' },
            { id: 148, label: 'Northern Mariana Islands', value: 'mp' },
            { id: 149, label: 'Martinique (French)', value: 'mq' },
            { id: 150, label: 'Mauritania', value: 'mr' },
            { id: 151, label: 'Montserrat', value: 'ms' },
            { id: 152, label: 'Malta', value: 'mt' },
            { id: 153, label: 'Mauritius', value: 'mu' },
            { id: 154, label: 'Maldives', value: 'mv' },
            { id: 155, label: 'Malawi', value: 'mw' },
            { id: 156, label: 'Mexico', value: 'mx' },
            { id: 157, label: 'Malaysia', value: 'my' },
            { id: 158, label: 'Mozambique', value: 'mz' },
            { id: 159, label: 'Namibia', value: 'na' },
            { id: 160, label: 'NATO (this was purged in 1996 - see hq.nato.int)', value: 'nato' },
            { id: 161, label: 'New Caledonia (French)', value: 'nc' },
            { id: 162, label: 'Niger', value: 'ne' },
            { id: 163, label: 'Network', value: 'net' },
            { id: 164, label: 'Norfolk Island', value: 'nf' },
            { id: 165, label: 'Nigeria', value: 'ng' },
            { id: 166, label: 'Nicaragua', value: 'ni' },
            { id: 167, label: 'Netherlands', value: 'nl' },
            { id: 168, label: 'Norway', value: 'no' },
            { id: 169, label: 'Nepal', value: 'np' },
            { id: 170, label: 'Nauru', value: 'nr' },
            { id: 171, label: 'Neutral Zone', value: 'nt' },
            { id: 172, label: 'Niue', value: 'nu' },
            { id: 173, label: 'New Zealand', value: 'nz' },
            { id: 174, label: 'Oman', value: 'om' },
            { id: 175, label: 'Non-Profit Making Organisations (sic)', value: 'org' },
            { id: 176, label: 'Panama', value: 'pa' },
            { id: 177, label: 'Peru', value: 'pe' },
            { id: 178, label: 'Polynesia (French)', value: 'pf' },
            { id: 179, label: 'Papua New Guinea', value: 'pg' },
            { id: 180, label: 'Philippines', value: 'ph' },
            { id: 181, label: 'Pakistan', value: 'pk' },
            { id: 182, label: 'Poland', value: 'pl' },
            { id: 183, label: 'Saint Pierre and Miquelon', value: 'pm' },
            { id: 184, label: 'Pitcairn Island', value: 'pn' },
            { id: 185, label: 'Puerto Rico', value: 'pr' },
            { id: 186, label: 'Portugal', value: 'pt' },
            { id: 187, label: 'Palau', value: 'pw' },
            { id: 188, label: 'Paraguay', value: 'py' },
            { id: 189, label: 'Qatar', value: 'qa' },
            { id: 190, label: 'Reunion (French)', value: 're' },
            { id: 191, label: 'Romania', value: 'ro' },
            { id: 192, label: 'Russian Federation', value: 'ru' },
            { id: 193, label: 'Rwanda', value: 'rw' },
            { id: 194, label: 'Saudi Arabia', value: 'sa' },
            { id: 195, label: 'Solomon Islands', value: 'sb' },
            { id: 196, label: 'Seychelles', value: 'sc' },
            { id: 197, label: 'Sudan', value: 'sd' },
            { id: 198, label: 'Sweden', value: 'se' },
            { id: 199, label: 'Singapore', value: 'sg' },
            { id: 200, label: 'Saint Helena', value: 'sh' },
            { id: 201, label: 'Slovenia', value: 'si' },
            { id: 202, label: 'Svalbard and Jan Mayen Islands', value: 'sj' },
            { id: 203, label: 'Slovak Republic', value: 'sk' },
            { id: 204, label: 'Sierra Leone', value: 'sl' },
            { id: 205, label: 'San Marino', value: 'sm' },
            { id: 206, label: 'Senegal', value: 'sn' },
            { id: 207, label: 'Somalia', value: 'so' },
            { id: 208, label: 'Suriname', value: 'sr' },
            { id: 209, label: 'Saint Tome (Sao Tome) and Principe', value: 'st' },
            { id: 210, label: 'Former USSR', value: 'su' },
            { id: 211, label: 'El Salvador', value: 'sv' },
            { id: 212, label: 'Syria', value: 'sy' },
            { id: 213, label: 'Swaziland', value: 'sz' },
            { id: 214, label: 'Turks and Caicos Islands', value: 'tc' },
            { id: 215, label: 'Chad', value: 'td' },
            { id: 216, label: 'French Southern Territories', value: 'tf' },
            { id: 217, label: 'Togo', value: 'tg' },
            { id: 218, label: 'Thailand', value: 'th' },
            { id: 219, label: 'Tadjikistan', value: 'tj' },
            { id: 220, label: 'Tokelau', value: 'tk' },
            { id: 221, label: 'Turkmenistan', value: 'tm' },
            { id: 222, label: 'Tunisia', value: 'tn' },
            { id: 223, label: 'Tonga', value: 'to' },
            { id: 224, label: 'East Timor', value: 'tp' },
            { id: 225, label: 'Turkey', value: 'tr' },
            { id: 226, label: 'Trinidad and Tobago', value: 'tt' },
            { id: 227, label: 'Tuvalu', value: 'tv' },
            { id: 228, label: 'Taiwan', value: 'tw' },
            { id: 229, label: 'Tanzania', value: 'tz' },
            { id: 230, label: 'Ukraine', value: 'ua' },
            { id: 231, label: 'Uganda', value: 'ug' },
            { id: 232, label: 'United Kingdom', value: 'uk' },
            { id: 233, label: 'USA Minor Outlying Islands', value: 'um' },
            { id: 234, label: 'United States', value: 'us' },
            { id: 235, label: 'Uruguay', value: 'uy' },
            { id: 236, label: 'Uzbekistan', value: 'uz' },
            { id: 237, label: 'Vatican City State', value: 'va' },
            { id: 238, label: 'Saint Vincent & Grenadines', value: 'vc' },
            { id: 239, label: 'Venezuela', value: 've' },
            { id: 240, label: 'Virgin Islands (British)', value: 'vg' },
            { id: 241, label: 'Virgin Islands (USA)', value: 'vi' },
            { id: 242, label: 'Vietnam', value: 'vn' },
            { id: 243, label: 'Vanuatu', value: 'vu' },
            { id: 244, label: 'Wallis and Futuna Islands', value: 'wf' },
            { id: 245, label: 'Samoa', value: 'ws' },
            { id: 246, label: 'Yemen', value: 'ye' },
            { id: 247, label: 'Mayotte', value: 'yt' },
            { id: 248, label: 'Yugoslavia', value: 'yu' },
            { id: 249, label: 'South Africa', value: 'za' },
            { id: 250, label: 'Zambia', value: 'zm' },
            { id: 251, label: 'Zaire', value: 'zr' },
            { id: 252, label: 'Zimbabwe', value: 'zw' }

          /*{
            id: 1,
            label: 'United States',
            value: 'us'
          }, {
            id: 2,
            label: 'Spain',
            value: 'es',
        }*/

        ],
        visible: true
    }, {
        fieldName: 'terms',
        fieldLabel: 'I accept the terms and conditions',
        inputType: 'checkbox',
        visible: true,
        saveToProfile: false,
        validate: function(value, errorFunction) {
            if (value) {
                return true;
            } else {
                errorFunction('You must accept the terms and conditions.');
                return false;
            }
        }
    }]
});


///////////////// end of account-ui cnfiguration ////////////////// 
